version: "3.8"

volumes:
  rabbitmq_data:
  postgres_volume:


services:

  backend:
    container_name: backend
    build: ../backend/
    restart: unless-stopped
    depends_on:
      - servicedb
      - rabbitmq
    env_file:
      - ./../.env
    ports:
      - '82:8888'
    networks:
      main:


  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    restart: unless-stopped
    env_file:
      - ./../.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      main:


  servicedb:
    container_name: servicedb
    build: ../service_db/
    restart: unless-stopped
    depends_on:
      - db
      - rabbitmq
    env_file:
      - ./../.env
    networks:
      main:


  db:
    container_name: postgresql_db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./../.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      main:
    ports:
      - "5433:5432"

  app:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ../frontend/static:/usr/share/nginx/html

networks:
  main:
